# Generated by Django 6.1.1 on 2026-10-02 23:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0005_tenant_audit_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Time')),
                ('source', models.CharField(db_index=True, max_length=100, verbose_name='Source')),
                ('event', models.CharField(db_index=True, max_length=50, verbose_name='Event')),
                ('level', models.PositiveSmallIntegerField(choices=[(2, 'Critical'), (3, 'Error'), (4, 'Warning'), (5, 'Success'), (6, 'Info')], default=6, verbose_name='Level')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Summary')),
                ('body', models.TextField(blank=True, verbose_name='Details')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Subject ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Subject type')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Journal entry',
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-timestamp', '-pk'],
            },
        ),
    ]
