# SPDX-FileCopyrightText: 2025 Thomas Breitner
#
# SPDX-License-Identifier: CC0-1.0

pages:
  stage: deploy
  image: python:3.11-slim
  before_script:
  - apt-get --assume-yes update && apt-get --assume-yes --no-install-recommends install libmagic1
  script:
  - pip install --upgrade pip setuptools wheel && pip install -r requirements/prod.txt
  - printf "SETTINGS_MODE=production\nDJANGO_DEBUG=false\n" > .env
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - main
