pages:
  stage: deploy
  image: python:3.10-slim
  script:
  - pip install --upgrade pip setuptools wheel && pip install -r requirements/requirements-prod.txt
  - echo "SETTINGS_MODE=production\nDJANGO_DEBUG=false" > .env
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - main
