# Generated by Django 4.0 on 2022-01-05 00:16

from django.db import migrations, models
import django.db.models.deletion
import dlcdb.reporting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv?')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Empfänger (Email To)')),
                ('recipient_cc', models.EmailField(blank=True, max_length=254, verbose_name='Empfänger (Email CC)')),
                ('event', models.CharField(choices=[('ORDERED', 'BESTELLT'), ('INROOM', 'LOKALISIERT'), ('LENT', 'VERLIEHEN'), ('LOST', 'NICHT AUFFINDBAR'), ('REMOVED', 'ENTFERNT')], max_length=20, verbose_name='Ereignis')),
                ('condition', models.CharField(blank=True, choices=[('LENT_IS_OVERDUE', 'Rückgabe überfällig'), ('IS_NEW_PC_OR_NOTEBOOK', 'Ist neuer PC oder Notebook'), ('IS_PC_OR_NOTEBOOK', 'Ist PC oder Notebook'), ('IS_PC', 'Ist PC'), ('IS_NOTEBOOK', 'Ist Notebook'), ('HAS_SAP_ID', 'Hat SAP-Nummer')], max_length=255, verbose_name='Bedingung')),
                ('time_interval', models.CharField(choices=[('DAILY', 'Täglich'), ('WEEKLY', 'Wöchentlich'), ('MONTHLY', 'Monatlich'), ('YEARLY', 'Jährlich'), ('EVERY_MINUTE', 'Minütlich')], default='WEEKLY', max_length=255)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('notify_no_updates', models.BooleanField(default=False, help_text='Benachrichtigungen erhalten, auch wenn keine Veränderungen stattgefunden haben. Nützlich, um die Email-Funktionalität zu testen.', verbose_name='Benachrichtigungen ohne Updates')),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('spreadsheet', models.FileField(blank=True, editable=False, upload_to=dlcdb.reporting.models.spreadsheet_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.notification')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
