# Generated by Django 5.1.2 on 2024-11-22 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_device_device_type_and_more'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Für Gerätebezogene Benachrichtigungen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='condition',
            field=models.CharField(blank=True, choices=[('LENT_IS_OVERDUE', 'Rückgabe überfällig'), ('IS_NEW_PC_OR_NOTEBOOK', 'Ist neuer PC oder Notebook'), ('IS_PC_OR_NOTEBOOK', 'Ist PC oder Notebook'), ('IS_PC', 'Ist PC'), ('IS_NOTEBOOK', 'Ist Notebook'), ('HAS_SAP_ID', 'Hat SAP-Nummer'), ('LICENCE_EXPIRES', 'Lizenz läuft ab')], max_length=255, verbose_name='Bedingung'),
        ),
    ]
