# Generated by Django 5.1.2 on 2024-12-12 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_device_contract_termination_date_and_more'),
        ('reporting', '0002_notification_device_alter_notification_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('CONTRACT_ADDED', 'Contract Added'), ('CONTRACT_EXPIRES_SOON', 'Contract Expires Soon'), ('CONTRACT_EXPIRED', 'Contract Expired'), ('MOVED', 'Moved'), ('DEVICE_DECOMMISSIONED', 'Device decommissioned')], max_length=255, verbose_name='Type of event')),
                ('interval', models.CharField(choices=[('immediately', 'Immediately'), ('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week'), ('monthly', 'Every Month'), ('yearly', 'Every Year')], max_length=255, verbose_name='Interval Name')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.device')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
