# Generated by Django 5.1.2 on 2024-12-16 10:04

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_device_contract_termination_date_and_more'),
        ('reporting', '0003_subscription_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='event',
            field=models.CharField(blank=True, choices=[('CONTRACT_ADDED', 'Contract Added'), ('CONTRACT_EXPIRES_SOON', 'Contract Expires Soon'), ('CONTRACT_EXPIRED', 'Contract Expired'), ('MOVED', 'Moved'), ('DEVICE_DECOMMISSIONED', 'Device decommissioned')], max_length=255, verbose_name='Type of event'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(blank=True, choices=[('immediately', 'Immediately'), ('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week'), ('monthly', 'Every Month'), ('yearly', 'Every Year')], max_length=255, verbose_name='Interval Name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person'),
        ),
        migrations.CreateModel(
            name='HistoricalSubscription',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('event', models.CharField(blank=True, choices=[('CONTRACT_ADDED', 'Contract Added'), ('CONTRACT_EXPIRES_SOON', 'Contract Expires Soon'), ('CONTRACT_EXPIRED', 'Contract Expired'), ('MOVED', 'Moved'), ('DEVICE_DECOMMISSIONED', 'Device decommissioned')], max_length=255, verbose_name='Type of event')),
                ('interval', models.CharField(blank=True, choices=[('immediately', 'Immediately'), ('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week'), ('monthly', 'Every Month'), ('yearly', 'Every Year')], max_length=255, verbose_name='Interval Name')),
                ('subscribed_at', models.DateTimeField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.device')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person')),
            ],
            options={
                'verbose_name': 'historical subscription',
                'verbose_name_plural': 'historical subscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
