# Generated by Django 5.1.4 on 2024-12-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_subscription_managers_alter_subscription_event_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subscription',
            managers=[
            ],
        ),
    ]
