# Generated by Django 6.0.6 on 2026-07-06 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_remove_message_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='notification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
