# Generated by Django 6.0.6 on 2026-07-07 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_record_lent_accessories_and_more'),
        ('notifications', '0001_initial'),
        ('reporting', '0007_remove_report_notification_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='condition',
            field=models.CharField(blank=True, choices=[('LENT_IS_OVERDUE', 'Return overdue'), ('IS_NEW_PC_OR_NOTEBOOK', 'Is new PC or notebook'), ('IS_PC_OR_NOTEBOOK', 'Is PC or notebook'), ('IS_PC', 'Is PC'), ('IS_NOTEBOOK', 'Is notebook'), ('HAS_SAP_ID', 'Has SAP number'), ('LICENCE_EXPIRES', 'Licence expires')], help_text='Only for report events: restrict which records are reported.', max_length=255, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='notify_no_updates',
            field=models.BooleanField(default=False, help_text='Also send an email when no records match. Useful for testing the email functionality.', verbose_name='Notify without updates'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='message',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.report'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='condition',
            field=models.CharField(blank=True, choices=[('LENT_IS_OVERDUE', 'Return overdue'), ('IS_NEW_PC_OR_NOTEBOOK', 'Is new PC or notebook'), ('IS_PC_OR_NOTEBOOK', 'Is PC or notebook'), ('IS_PC', 'Is PC'), ('IS_NOTEBOOK', 'Is notebook'), ('HAS_SAP_ID', 'Has SAP number'), ('LICENCE_EXPIRES', 'Licence expires')], help_text='Only for report events: restrict which records are reported.', max_length=255, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='notify_no_updates',
            field=models.BooleanField(default=False, help_text='Also send an email when no records match. Useful for testing the email functionality.', verbose_name='Notify without updates'),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='event',
            field=models.CharField(choices=[('CONTRACT_ADDED', 'Contract Added'), ('CONTRACT_EXPIRES_SOON', 'Contract Expires Soon'), ('CONTRACT_EXPIRED', 'Contract Expired'), ('MOVED', 'Moved'), ('DEVICE_DECOMMISSIONED', 'Device decommissioned'), ('ORDERED', 'Report: Ordered devices'), ('INROOM', 'Report: Located devices'), ('LENT', 'Report: Lent devices'), ('LOST', 'Report: Lost devices'), ('REMOVED', 'Report: Removed devices')], max_length=255, verbose_name='Type of event'),
        ),
        migrations.AlterField(
            model_name='historicalsubscription',
            name='interval',
            field=models.CharField(choices=[('point_in_time', 'Specific Date/Time'), ('immediately', 'Immediately'), ('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week'), ('monthly', 'Every Month'), ('yearly', 'Every Year')], default='weekly', max_length=255, verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.subscription'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='event',
            field=models.CharField(choices=[('CONTRACT_ADDED', 'Contract Added'), ('CONTRACT_EXPIRES_SOON', 'Contract Expires Soon'), ('CONTRACT_EXPIRED', 'Contract Expired'), ('MOVED', 'Moved'), ('DEVICE_DECOMMISSIONED', 'Device decommissioned'), ('ORDERED', 'Report: Ordered devices'), ('INROOM', 'Report: Located devices'), ('LENT', 'Report: Lent devices'), ('LOST', 'Report: Lost devices'), ('REMOVED', 'Report: Removed devices')], max_length=255, verbose_name='Type of event'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('point_in_time', 'Specific Date/Time'), ('immediately', 'Immediately'), ('hourly', 'Every Hour'), ('daily', 'Every Day'), ('weekly', 'Every Week'), ('monthly', 'Every Month'), ('yearly', 'Every Year')], default='weekly', max_length=255, verbose_name='Interval'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.person'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('subscription__isnull', False), models.Q(('recipient_email', ''), _negated=True), _connector='OR'), name='message_has_recipient_source'),
        ),
    ]
