# Generated by Django 6.0.6 on 2026-07-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_historicalsubscription_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cc_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
