# Generated by Django 6.1.1 on 2026-10-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_drop_repeated_subscription_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='last_run',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='last_sent',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='historicalsubscription',
            name='next_scheduled',
        ),
    ]
