# Generated by Django 4.0.1 on 2022-02-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='SapList',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('file', models.FileField(upload_to='sap_csv', verbose_name='CSV-Datei')),
        #         ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum')),
        #         ('note', models.TextField(blank=True, null=True, verbose_name='Anmerkung')),
        #     ],
        #     options={
        #         'verbose_name': 'SAP-Liste',
        #         'verbose_name_plural': 'SAP-Listen',
        #     },
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SapList',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('file', models.FileField(upload_to='sap_csv', verbose_name='CSV-Datei')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum')),
                        ('note', models.TextField(blank=True, null=True, verbose_name='Anmerkung')),
                    ],
                ),
            ],
            # Table already exists. See core/migrations/0018
            database_operations=[],
        ),
        # migrations.CreateModel(
        #     name='SapListComparisonResult',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('file_name', models.CharField(blank=True, max_length=255, null=True)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('sap_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.saplist')),
        #     ],
        #     options={
        #         'ordering': ('-created_at',),
        #     },
        # ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SapListComparisonResult',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('sap_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.saplist')),
                    ],
                ),
            ],
            # Table already exists. See core/migrations/0018
            database_operations=[],
        ),
    ]
