# Generated by Django 4.0.3 on 2022-03-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LendingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lending_preparation_checklist', models.TextField(help_text="Basic Markdown supported. '[ ]' converted to checkbox input.")),
            ],
            options={
                'verbose_name': 'Lending Configuration',
                'verbose_name_plural': 'Lending Configuration',
            },
        ),
    ]
