# Generated by Django 4.1.4 on 2022-12-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lendingconfiguration",
            name="lending_preparation_checklist",
            field=models.TextField(
                blank=True, help_text="Basic Markdown supported. '[ ]' converted to checkbox input."
            ),
        ),
    ]
