# Generated by Django 5.0.2 on 2024-02-26 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_link'),
        ('lending', '0002_alter_lendingconfiguration_lending_preparation_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingConfigurationRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lending_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.lendingconfiguration')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.link')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lending_configuration', 'regulation')},
            },
        ),
        migrations.AddField(
            model_name='lendingconfiguration',
            name='mandatory_regulations',
            field=models.ManyToManyField(related_name='+', through='lending.LendingConfigurationRegulation', to='core.link'),
        ),
    ]
