# Generated by Django 5.0.1 on 2024-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_link'),
        ('lending', '0002_alter_lendingconfiguration_lending_preparation_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingconfiguration',
            name='mandatory_regulations',
            field=models.ManyToManyField(blank=True, to='core.link'),
        ),
    ]
