# Generated by Django 5.1.4 on 2025-01-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_lendingconfigurationregulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingconfiguration',
            name='admin_mark_overdue',
            field=models.BooleanField(default=True, help_text='If checked, the admin listing highlights overdue devices.'),
        ),
    ]
