# Generated by Django 6.0.3 on 2026-03-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_lostrecord_options_alter_removedrecord_options'),
        ('lending', '0004_lendingconfiguration_admin_mark_overdue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lending_preparation_checklist', models.TextField(blank=True, help_text="Basic Markdown supported. '[ ]' converted to checkbox input.")),
                ('lent_sheet_template', models.TextField(blank=True, help_text="Django template syntax. Should {% extends 'lending/printout_base.html' %}. Available context: record, lending_profile, sheet_for, pagebreak.")),
                ('device_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lending_profile', to='core.devicetype', verbose_name='Device Type')),
            ],
            options={
                'verbose_name': 'Lending Profile',
                'verbose_name_plural': 'Lending Profiles',
            },
        ),
        migrations.CreateModel(
            name='LendingProfileRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lending_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending.lendingprofile')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.link')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('lending_profile', 'regulation')},
            },
        ),
        migrations.AddField(
            model_name='lendingprofile',
            name='mandatory_regulations',
            field=models.ManyToManyField(blank=True, related_name='+', through='lending.LendingProfileRegulation', to='core.link'),
        ),
    ]
