# Generated by Django 6.0.7 on 2026-07-28 17:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_translate_record_type_labels'),
        ('lending', '0005_lendingprofile_lendingprofileregulation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingconfiguration',
            name='overdue_notifications_recipient',
            field=models.CharField(choices=[('none', 'Nobody — no overdue mails'), ('lender', 'Lender'), ('lender_and_it', 'Lender, IT in CC'), ('it', 'IT only (testdrive: lender mails rerouted to IT)')], default='lender', help_text='Who receives the weekly overdue-lending reminder mails. The IT address is resolved per tenant: tenant contact email → Branding IT dept email → DEFAULT_FROM_EMAIL.', max_length=20),
        ),
        migrations.CreateModel(
            name='HistoricalLendingProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('lending_preparation_checklist', models.TextField(blank=True, help_text="Basic Markdown supported. '[ ]' converted to checkbox input.")),
                ('lent_sheet_template', models.TextField(blank=True, help_text="Django template syntax. Should {% extends 'lending/printout_base.html' %}. Available context: record, lending_profile, sheet_for, pagebreak.")),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('device_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.devicetype', verbose_name='Device Type')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Lending Profile',
                'verbose_name_plural': 'historical Lending Profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
