# Generated by Django 6.0.6 on 2026-07-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_populate_lending_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingconfiguration',
            name='overdue_notifications_recipient',
            field=models.CharField(choices=[('none', 'Nobody — no overdue mails'), ('lender', 'Lender'), ('lender_and_it', 'Lender, IT in CC'), ('it', 'IT only (testdrive: lender mails rerouted to IT)')], default='lender', help_text='Who receives the weekly overdue-lending reminder mails. IT = DEFAULT_FROM_EMAIL.', max_length=20),
        ),
    ]
