# Generated by Django 6.0.6 on 2026-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0007_lendingconfiguration_overdue_notifications_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingconfiguration',
            name='overdue_notifications_recipient',
            field=models.CharField(choices=[('none', 'Nobody — no overdue mails'), ('lender', 'Lender'), ('lender_and_it', 'Lender, IT in CC'), ('it', 'IT only (testdrive: lender mails rerouted to IT)')], default='lender', help_text='Who receives the weekly overdue-lending reminder mails. The IT address is resolved per tenant: tenant contact email → Branding IT dept email → DEFAULT_FROM_EMAIL.', max_length=20),
        ),
    ]
