# Generated by Django 6.0.7 on 2026-07-28 23:10

import dlcdb.lending.starter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0009_historicallendingprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallendingprofile',
            name='lending_preparation_checklist',
            field=models.TextField(blank=True, default=dlcdb.lending.starter.get_starter_lending_preparation_checklist, help_text="Basic Markdown supported. '[ ]' converted to checkbox input."),
        ),
        migrations.AlterField(
            model_name='historicallendingprofile',
            name='lent_sheet_template',
            field=models.TextField(blank=True, default=dlcdb.lending.starter.get_starter_lent_sheet_template, help_text="Django template syntax. Should {% extends 'lending/printout_base.html' %}. Available context: record, lending_profile. The sheet body and the checklist are {% include %}d from 'lending/includes/', parameterized with sheet_for and pagebreak."),
        ),
        migrations.AlterField(
            model_name='lendingprofile',
            name='lending_preparation_checklist',
            field=models.TextField(blank=True, default=dlcdb.lending.starter.get_starter_lending_preparation_checklist, help_text="Basic Markdown supported. '[ ]' converted to checkbox input."),
        ),
        migrations.AlterField(
            model_name='lendingprofile',
            name='lent_sheet_template',
            field=models.TextField(blank=True, default=dlcdb.lending.starter.get_starter_lent_sheet_template, help_text="Django template syntax. Should {% extends 'lending/printout_base.html' %}. Available context: record, lending_profile. The sheet body and the checklist are {% include %}d from 'lending/includes/', parameterized with sheet_for and pagebreak."),
        ),
    ]
