# SPDX-FileCopyrightText: Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

"""
The ``audit_field_losses`` command: what it finds, and what it refuses to touch.
"""

import datetime
from io import StringIO

import pytest
from django.core.management import CommandError, call_command

from dlcdb.core.management.commands.audit_field_losses import find_field_losses
from dlcdb.core.models import Device

pytestmark = pytest.mark.django_db


def _device_with_a_lost_purchase_date():
    """A device whose purchase date was set, then cleared by a later save."""
    device = Device.objects.create(edv_id="EDV-LOSS", purchase_date=datetime.date(2026, 1, 15))
    device.purchase_date = None
    device.save()
    return device


def _run(*args):
    out = StringIO()
    call_command("audit_field_losses", *args, stdout=out)
    return out.getvalue()


def test_a_cleared_field_is_reported_as_a_loss():
    device = _device_with_a_lost_purchase_date()

    (loss,) = find_field_losses(device_pk=device.pk)

    assert loss.field == "purchase_date"
    assert loss.old_value == datetime.date(2026, 1, 15)
    assert loss.still_empty is True


def test_a_value_re_entered_after_the_loss_is_reported_but_not_restorable():
    device = _device_with_a_lost_purchase_date()
    device.purchase_date = datetime.date(2026, 3, 1)
    device.save()

    (loss,) = find_field_losses(device_pk=device.pk)
    assert loss.still_empty is False

    _run("--restore", "--all")

    device.refresh_from_db()
    assert device.purchase_date == datetime.date(2026, 3, 1), "a re-entered value must not be overwritten"


def test_booleans_and_machine_managed_fields_are_not_losses():
    device = Device.objects.create(edv_id="EDV-FLAGS", is_lentable=True)
    device.is_lentable = False  # False is a value, not a missing one
    device.qrcode = ""  # regenerated by Device.save(), never user data
    device.save()

    assert find_field_losses(device_pk=device.pk) == []


def test_reporting_alone_writes_nothing():
    device = _device_with_a_lost_purchase_date()
    revisions = device.history.count()

    output = _run()

    assert "purchase_date" in output
    assert "still empty" in output
    device.refresh_from_db()
    assert device.purchase_date is None
    assert device.history.count() == revisions, "a report must not create a revision"


def test_restore_writes_the_value_back_with_an_audit_trail():
    device = _device_with_a_lost_purchase_date()

    output = _run("--restore", "--device", str(device.pk))

    device.refresh_from_db()
    assert device.purchase_date == datetime.date(2026, 1, 15)
    assert "Restored 1 value(s)" in output
    assert "purchase_date" in device.history.first().history_change_reason


def test_restore_only_touches_the_named_device():
    lost = _device_with_a_lost_purchase_date()
    other = Device.objects.create(edv_id="EDV-OTHER", purchase_date=datetime.date(2026, 2, 1))
    other.purchase_date = None
    other.save()

    _run("--restore", "--device", str(lost.pk))

    other.refresh_from_db()
    assert other.purchase_date is None


def test_restore_can_be_narrowed_to_one_field():
    device = Device.objects.create(
        edv_id="EDV-TWO-FIELDS",
        purchase_date=datetime.date(2026, 1, 15),
        book_value="1499.00",
    )
    device.purchase_date = None
    device.book_value = ""
    device.save()

    _run("--restore", "--device", str(device.pk), "--field", "purchase_date")

    device.refresh_from_db()
    assert device.purchase_date == datetime.date(2026, 1, 15)
    assert device.book_value == ""


def test_restore_without_a_target_is_refused():
    _device_with_a_lost_purchase_date()

    with pytest.raises(CommandError, match="--restore needs --device"):
        _run("--restore")
