# Generated by Django 5.1.2 on 2024-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0057_device_contract_termination_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensesConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_subscribers', models.ManyToManyField(blank=True, help_text='These subscribers will be added to all new licenses by default.', related_name='+', to='core.person')),
            ],
            options={
                'verbose_name': 'Licenses configuration',
                'verbose_name_plural': 'Licenses configuration',
            },
        ),
    ]
