# Generated by Django 5.2.1 on 2025-05-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_device_contact_person_internal_and_more'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAsset',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.device',),
        ),
    ]
