# Generated by Django 4.0 on 2022-01-07 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_is_super_tenant'),
        ('core', '0002_device_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant'),
        ),
    ]
