# Generated by Django 4.0 on 2022-01-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_device_tenant'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='device',
        #     name='affiliation',
        # ),
        migrations.AlterField(
            model_name='importerlist',
            name='file',
            field=models.FileField(help_text='Valide Spaltenköpfe: <br>SAP_ID<br>ROOM<br>EDV_ID<br>DEVICE_TYPE<br>SERIAL_NUMBER<br>MANUFACTURER<br>SERIES<br>SUPPLIER<br>PURCHASE_DATE<br>WARRANTY_EXPIRATION_DATE<br>MAINTENANCE_CONTRACT_EXPIRATION_DATE<br>COST_CENTRE<br>BOOK_VALUE<br>NOTE<br>MAC_ADDRESS<br>EXTRA_MAC_ADDRESSES<br>NICK_NAME<br>IS_LENTABLE<br>USERNAME<br>TENANT', upload_to='imported_csv', verbose_name='CSV-Datei'),
        ),
    ]
