# Generated by Django 4.0 on 2022-01-09 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_device_affiliation_alter_importerlist_file'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Affiliation',
        # ),
    ]
