# Generated by Django 4.0.1 on 2022-01-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_affiliation'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='importerlist',
        #     name='file',
        #     field=models.FileField(help_text='Valide Spaltenköpfe: <br>SAP_ID<br>ROOM<br>EDV_ID<br>DEVICE_TYPE<br>SERIAL_NUMBER<br>MANUFACTURER<br>SERIES<br>SUPPLIER<br>PURCHASE_DATE<br>WARRANTY_EXPIRATION_DATE<br>MAINTENANCE_CONTRACT_EXPIRATION_DATE<br>COST_CENTRE<br>BOOK_VALUE<br>NOTE<br>MAC_ADDRESS<br>EXTRA_MAC_ADDRESSES<br>NICK_NAME<br>IS_LENTABLE<br>IS_LICENCE<br>USERNAME<br>TENANT', upload_to='imported_csv', verbose_name='CSV-Datei'),
        # ),
    ]
