# Generated by Django 4.0.1 on 2022-01-23 23:10

from django.db import migrations, models
import dlcdb.core.models.room


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_importerlist_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReconcile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Aktuell werden nur Archibus-CSV-Exportdateien unterstützt.', upload_to=dlcdb.core.models.room.timestamped_file_path, verbose_name='Datei')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellungsdatum')),
                ('note', models.TextField(blank=True, verbose_name='Anmerkung')),
            ],
            options={
                'verbose_name': 'Raum-Abgleich',
                'verbose_name_plural': 'Raum-Abgleich',
                'ordering': ['created_at'],
            },
        ),
    ]
