# Generated by Django 4.0.1 on 2022-01-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_importerlist_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='udb_contract_contract_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_contract_organization_unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_contract_organizational_positions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_contract_planned_checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_contract_planned_checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_data_updated_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_person_email_internal_business',
            field=models.EmailField(blank=True, max_length=320, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_person_email_private',
            field=models.EmailField(blank=True, max_length=320, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_person_first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='udb_person_last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
