# Generated by Django 4.0.1 on 2022-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_person_created_at_person_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='IMMER eine Email-Adresse angeben, da wir sonst die Ausleiher nicht anschreiben können.', max_length=254, null=True, unique=True),
        ),
    ]
