# Generated by Django 4.0.1 on 2022-01-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_person_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
