# Generated by Django 4.0.1 on 2022-01-31 10:20

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_person_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('first_name'), django.db.models.functions.text.Lower('last_name'), name='unique_dlcdb_person_name'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('udb_person_first_name'), django.db.models.functions.text.Lower('udb_person_last_name'), name='unique_udb_person_name'),
        ),
    ]
