# Generated by Django 4.0.1 on 2022-01-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_person_unique_dlcdb_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='udb_person_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
