# Generated by Django 4.0.1 on 2022-01-31 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_person_udb_person_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sap_id',
            field=models.CharField(blank=True, help_text='Format: `Hauptnummer-Unternummer`. Für Anlagen die ausschließlich eine Hauptnummer besitzen, ist die 0 (Null) als Unternummer einzutragen.', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_sap_id', message='SAP-ID muss als Hauptnummer-Unternummer eingegeben werden.', regex='^[0-9]+-[0-9]+$')], verbose_name='SAP-Nummer'),
        ),
    ]
