# Generated by Django 4.0.1 on 2022-02-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_device_sap_id_validator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DialogDevice',
        ),
    ]
