# Generated by Django 4.0.1 on 2022-02-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_dialogdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryRoom',
        ),
    ]
