# Generated by Django 4.0.3 on 2022-03-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_historicaldevice_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bestellnummer (SAP)'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bestellnummer (SAP)'),
        ),
    ]
