# Generated by Django 4.0.4 on 2022-05-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_historicaldevice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, choices=[('edv', 'EDV'), ('bib', 'Bibliothek'), ('vrw', 'Verwaltung'), ('str', 'Strafrecht'), ('krm', 'Kriminologie'), ('psl', 'Öffentliches Recht/Public Law'), ('htk', 'Haustechnik'), ('pic', 'RG Personality, Identity, and Crime'), ('scc', 'RG Space, Contexts, and Crime'), ('rgs', 'RG Strafrechtstheorie')], max_length=3),
        ),
    ]
