# Generated by Django 4.0.5 on 2022-06-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_person_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='udb_person_image',
            field=models.ImageField(blank=True, upload_to='person_images/'),
        ),
    ]
