# Generated by Django 4.0.5 on 2022-06-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_organizationalunit_person_organizational_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
    ]
