# Generated by Django 4.1.3 on 2022-11-20 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_device_former_nick_names_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Name")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="manufacturer_name_unique"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="manufacturer_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="historicaldevice",
            name="manufacturer_fk",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
    ]
