# Generated by Django 4.1.3 on 2022-11-20 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_migrate_manufacturer_from_charfield_to_fkfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="historicaldevice",
            name="manufacturer",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="manufacturer_fk",
            new_name="manufacturer",
        ),
        migrations.RenameField(
            model_name="historicaldevice",
            old_name="manufacturer_fk",
            new_name="manufacturer",
        ),
    ]
