# Generated by Django 4.1.3 on 2022-11-25 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_manufacturer_fk_now_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="sap_id",
            field=models.CharField(
                blank=True,
                help_text="SAP-Nummer. Format: `Hauptnummer-Unternummer`. Für Anlagen die ausschließlich eine Hauptnummer besitzen, ist die 0 (Null) als Unternummer einzutragen.",
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_sap_id",
                        message="Inventarnummer muss als Hauptnummer-Unternummer eingegeben werden.",
                        regex="^[0-9]+-[0-9]+$",
                    )
                ],
                verbose_name="Inventory ID",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="sap_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SAP-Nummer. Format: `Hauptnummer-Unternummer`. Für Anlagen die ausschließlich eine Hauptnummer besitzen, ist die 0 (Null) als Unternummer einzutragen.",
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_sap_id",
                        message="Inventarnummer muss als Hauptnummer-Unternummer eingegeben werden.",
                        regex="^[0-9]+-[0-9]+$",
                    )
                ],
                verbose_name="Inventory ID",
            ),
        ),
    ]
