# Generated by Django 4.1.3 on 2022-11-26 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_device_sap_id_alter_historicaldevice_sap_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="has_malfunction",
        ),
        migrations.RemoveField(
            model_name="device",
            name="is_deinventorized",
        ),
        migrations.RemoveField(
            model_name="historicaldevice",
            name="has_malfunction",
        ),
        migrations.RemoveField(
            model_name="historicaldevice",
            name="is_deinventorized",
        ),
        migrations.AlterField(
            model_name="device",
            name="edv_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True, unique=True, verbose_name="EDV-Nummer"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="is_lentable",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is loanable?"),
        ),
        migrations.AlterField(
            model_name="device",
            name="sap_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SAP-Nummer. Format: `Hauptnummer-Unternummer`. Für Anlagen die ausschließlich eine Hauptnummer besitzen, ist die 0 (Null) als Unternummer einzutragen.",
                max_length=30,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_sap_id",
                        message="Inventarnummer muss als Hauptnummer-Unternummer eingegeben werden.",
                        regex="^[0-9]+-[0-9]+$",
                    )
                ],
                verbose_name="Inventory ID",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="is_lentable",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is loanable?"),
        ),
    ]
