# Generated by Django 4.1.3 on 2022-11-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_remove_device_has_malfunction_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lostrecord",
            options={"verbose_name": "Record of type 'Lost'", "verbose_name_plural": "Records of type 'Lost'"},
        ),
    ]
