# Generated by Django 4.1.4 on 2022-12-16 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_lostrecord_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["number"], "verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
        migrations.AddField(
            model_name="room",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="importerlist",
            name="file",
            field=models.FileField(
                help_text="Valide Spaltenköpfe: <br>SAP_ID<br>ROOM<br>EDV_ID<br>DEVICE_TYPE<br>SERIAL_NUMBER<br>MANUFACTURER<br>SERIES<br>SUPPLIER<br>PURCHASE_DATE<br>WARRANTY_EXPIRATION_DATE<br>MAINTENANCE_CONTRACT_EXPIRATION_DATE<br>COST_CENTRE<br>BOOK_VALUE<br>NOTE<br>MAC_ADDRESS<br>EXTRA_MAC_ADDRESSES<br>NICK_NAME<br>IS_LENTABLE<br>IS_LICENCE<br>USERNAME<br>TENANT<br>RECORD_TYPE<br>RECORD_NOTE<br>PERSON",
                upload_to="imported_csv",
                verbose_name="CSV-Datei",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"),
        ),
    ]
