# Generated by Django 4.1.4 on 2022-12-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_room_options_room_note_alter_importerlist_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devicetype",
            options={"ordering": ("name",), "verbose_name": "Device Type", "verbose_name_plural": "Device Types"},
        ),
        migrations.AddField(
            model_name="devicetype",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="devicetype",
            name="prefix",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
