# Generated by Django 4.1.4 on 2022-12-20 10:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_devicetype_options_devicetype_note_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lentrecord",
            options={"verbose_name": "Lending", "verbose_name_plural": "Lendings"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": [django.db.models.functions.text.Upper("name")],
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
        migrations.AddField(
            model_name="supplier",
            name="contact",
            field=models.TextField(
                blank=True, help_text="Contact and support information: contact persons, hotlines, mail addresses etc."
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.supplier",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.supplier",
                verbose_name="Supplier",
            ),
        ),
    ]
