# Generated by Django 4.1.4 on 2022-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_alter_lentrecord_options_alter_supplier_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="effective_until",
            field=models.DateTimeField(
                blank=True, help_text="Replaced by the next record at this timestamp.", null=True
            ),
        ),
    ]
