# Generated by Django 4.1.5 on 2023-02-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_record_effective_until"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="disposition_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SLD", "Sold"),
                    ("SCR", "Scrapped"),
                    ("SRD", "Surrendered"),
                    ("STL", "Stolen"),
                    ("DPL", "Duplicate"),
                ],
                max_length=3,
                verbose_name="Whereabouts after decommissioning",
            ),
        ),
    ]
