# Generated by Django 4.1.5 on 2023-03-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_tenant_options"),
        ("core", "0039_alter_record_disposition_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="importerlist",
            name="import_format",
            field=models.CharField(
                choices=[("INTCSV", "Internal (CSV)"), ("SAPCSV", "SAP (CSV)")],
                default="INTCSV",
                help_text="Specifiy the format of the import file. Currently officially supported is only 'INTCSV,'.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="importerlist",
            name="tenant",
            field=models.ForeignKey(
                help_text="Import as given tenant.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.tenant",
            ),
        ),
    ]
