# Generated by Django 4.1.5 on 2023-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_importerlist_import_format_importerlist_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="cost_centre",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Cost centre"),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="cost_centre",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Cost centre"),
        ),
        migrations.AlterField(
            model_name="importerlist",
            name="file",
            field=models.FileField(
                help_text="Valide Spaltenköpfe: <br>SAP_ID<br>ROOM<br>EDV_ID<br>DEVICE_TYPE<br>SERIAL_NUMBER<br>MANUFACTURER<br>SERIES<br>SUPPLIER<br>PURCHASE_DATE<br>WARRANTY_EXPIRATION_DATE<br>MAINTENANCE_CONTRACT_EXPIRATION_DATE<br>COST_CENTRE<br>BOOK_VALUE<br>NOTE<br>MAC_ADDRESS<br>EXTRA_MAC_ADDRESSES<br>NICK_NAME<br>IS_LENTABLE<br>IS_LICENCE<br>RECORD_TYPE<br>RECORD_NOTE<br>PERSON<br>REMOVED_DATE<br>ORDER_NUMBER",
                upload_to="imported_csv",
                verbose_name="CSV-Datei",
            ),
        ),
    ]
