# Generated by Django 4.1.8 on 2023-05-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_device_cost_centre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="created_by",
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="note",
            name="updated_by",
            field=models.EmailField(blank=True, editable=False, max_length=254),
        ),
    ]
