# Generated by Django 4.2.3 on 2023-07-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_alter_record_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="backup_encryption_key",
            field=models.TextField(
                blank=True,
                help_text="E.g. macOS TimeMachine password for backup hard disk.",
                verbose_name="Password backup encryption",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.devicetype",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="is_licence",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is license?"),
        ),
        migrations.AlterField(
            model_name="device",
            name="machine_encryption_key",
            field=models.TextField(
                blank=True,
                help_text="E.g. Bitlocker recovery key or macOS FileVault password for system hard disk.",
                verbose_name="Password Hard Disk Encryption",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Serial number"),
        ),
        migrations.AlterField(
            model_name="device",
            name="series",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Model name"),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="backup_encryption_key",
            field=models.TextField(
                blank=True,
                help_text="E.g. macOS TimeMachine password for backup hard disk.",
                verbose_name="Password backup encryption",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="device_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.devicetype",
                verbose_name="Device type",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="is_licence",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Is license?"),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="machine_encryption_key",
            field=models.TextField(
                blank=True,
                help_text="E.g. Bitlocker recovery key or macOS FileVault password for system hard disk.",
                verbose_name="Password Hard Disk Encryption",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="serial_number",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Serial number"),
        ),
        migrations.AlterField(
            model_name="historicaldevice",
            name="series",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Model name"),
        ),
        migrations.AlterField(
            model_name="record",
            name="assigned_device",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_licence": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_device",
                to="core.device",
                verbose_name="Assigned device",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.inventory",
                verbose_name="Inventory",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="record",
            name="note",
            field=models.TextField(blank=True, verbose_name="Record note"),
        ),
        migrations.AlterField(
            model_name="record",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("ORDERED", "BESTELLT"),
                    ("INROOM", "LOKALISIERT"),
                    ("LENT", "VERLIEHEN"),
                    ("LOST", "NICHT AUFFINDBAR"),
                    ("REMOVED", "ENTFERNT"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Record type",
            ),
        ),
    ]
