# Generated by Django 4.2.3 on 2023-07-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_device_backup_encryption_key_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["edv_id", "sap_id", "modified_at"], name="core_device_edv_id_78a1a2_idx"),
        ),
    ]
