# Generated by Django 4.2.3 on 2023-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_device_core_device_edv_id_78a1a2_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="devicetype",
            index=models.Index(fields=["name"], name="core_device_name_26f5fa_idx"),
        ),
        migrations.AddIndex(
            model_name="manufacturer",
            index=models.Index(fields=["name"], name="core_manufa_name_86be6b_idx"),
        ),
        migrations.AddIndex(
            model_name="record",
            index=models.Index(fields=["is_active", "record_type", "inventory"], name="core_record_is_acti_da802d_idx"),
        ),
    ]
