# Generated by Django 4.2.3 on 2023-07-17 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_devicetype_core_device_name_26f5fa_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_notes",
                to="core.inventory",
                verbose_name="Inventurzuordnung",
            ),
        ),
    ]
