# Generated by Django 4.2.3 on 2023-07-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_note_core_note_created_2f921c_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="removerlist",
            name="file",
            field=models.FileField(
                help_text="Valide Spaltenköpfe: <br>SAP_ID<br>EDV_ID<br>NOTE<br>DISPOSITION_STATE<br>REMOVED_INFO<br>REMOVED_DATE<br>USERNAME",
                upload_to="toremove_csv",
                verbose_name="CSV-Datei",
            ),
        ),
    ]
