# Generated by Django 5.0.8 on 2024-09-02 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_record_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='person',
            field=models.ForeignKey(blank=True, limit_choices_to={'deleted_at__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.person', verbose_name='Person'),
        ),
    ]
