# Generated by Django 5.1.2 on 2024-11-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_default_license_room',
            field=models.BooleanField(default=False, help_text='Room or location where the license information is stored.', verbose_name='Default license room'),
        ),
    ]
