# Generated by Django 5.1.2 on 2024-12-03 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_room_is_default_license_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date of licence or maintenance contract'),
        ),
        migrations.AddField(
            model_name='device',
            name='procurement_note',
            field=models.TextField(blank=True, help_text='Information such as unique selling points, possible suppliers for comparative offers, etc.', null=True, verbose_name='Procurement note'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date of licence or maintenance contract'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='procurement_note',
            field=models.TextField(blank=True, help_text='Information such as unique selling points, possible suppliers for comparative offers, etc.', null=True, verbose_name='Procurement note'),
        ),
        migrations.AlterField(
            model_name='device',
            name='book_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Book value'),
        ),
        migrations.AlterField(
            model_name='device',
            name='edv_id',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, unique=True, verbose_name='IT ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='extra_mac_addresses',
            field=models.TextField(blank=True, null=True, verbose_name='Further MAC addresses'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='Added via CSV import?'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_legacy',
            field=models.BooleanField(default=False, verbose_name='Legacy device'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main MAC address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='maintenance_contract_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry date licence or maintenance contract'),
        ),
        migrations.AlterField(
            model_name='device',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='device',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of purchase'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sap_id',
            field=models.CharField(blank=True, db_index=True, help_text='SAP-Nummer. Format: `Hauptnummer-Unternummer`. Für Anlagen die ausschließlich eine Hauptnummer besitzen, ist die 0 (Null) als Unternummer einzutragen.', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_sap_id', message='Inventory number must be entered as the main number-sub-number.', regex='^[0-9]+-[0-9]+$')], verbose_name='Inventory ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warranty_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty expiry date'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='book_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Book value'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='edv_id',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True, verbose_name='IT ID'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='extra_mac_addresses',
            field=models.TextField(blank=True, null=True, verbose_name='Further MAC addresses'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='Added via CSV import?'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='is_legacy',
            field=models.BooleanField(default=False, verbose_name='Legacy device'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main MAC address'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='maintenance_contract_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry date licence or maintenance contract'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='order_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Order number'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of purchase'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='sap_id',
            field=models.CharField(blank=True, db_index=True, help_text='SAP-Nummer. Format: `Hauptnummer-Unternummer`. Für Anlagen die ausschließlich eine Hauptnummer besitzen, ist die 0 (Null) als Unternummer einzutragen.', max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid_sap_id', message='Inventory number must be entered as the main number-sub-number.', regex='^[0-9]+-[0-9]+$')], verbose_name='Inventory ID'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='warranty_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Warranty expiry date'),
        ),
    ]
