# Generated by Django 5.1.2 on 2024-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_device_contract_start_date_device_procurement_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='maintenance_contract_expiration_date',
            new_name='contract_expiration_date',
        ),
        migrations.RenameField(
            model_name='historicaldevice',
            old_name='maintenance_contract_expiration_date',
            new_name='contract_expiration_date',
        ),
        migrations.AlterField(
            model_name='importerlist',
            name='file',
            field=models.FileField(help_text='Valide Spaltenköpfe: <br>SAP_ID<br>ROOM<br>EDV_ID<br>DEVICE_TYPE<br>SERIAL_NUMBER<br>MANUFACTURER<br>SERIES<br>SUPPLIER<br>PURCHASE_DATE<br>WARRANTY_EXPIRATION_DATE<br>CONTRACT_EXPIRATION_DATE<br>COST_CENTRE<br>BOOK_VALUE<br>NOTE<br>MAC_ADDRESS<br>EXTRA_MAC_ADDRESSES<br>NICK_NAME<br>IS_LENTABLE<br>IS_LICENCE<br>RECORD_TYPE<br>RECORD_NOTE<br>PERSON<br>REMOVED_DATE<br>ORDER_NUMBER', upload_to='imported_csv', verbose_name='CSV-Datei'),
        ),
    ]
