# Generated by Django 5.1.2 on 2024-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_rename_maintenance_contract_expiration_date_device_contract_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='contract_termination_date',
            field=models.DateField(blank=True, help_text='Date of termination of the contract.', null=True, verbose_name='Contract termination date'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='contract_termination_date',
            field=models.DateField(blank=True, help_text='Date of termination of the contract.', null=True, verbose_name='Contract termination date'),
        ),
    ]
