# Generated by Django 5.1.5 on 2025-02-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_device_contract_termination_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencerecord',
            options={'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
    ]
