# Generated by Django 5.2 on 2025-05-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_licencerecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='contact_person_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='device_contact_internal', to='core.person', verbose_name='Contact (internal)'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='contact_person_internal',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.person', verbose_name='Contact (internal)'),
        ),
    ]
