# Generated by Django 5.2.1 on 2025-05-30 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_device_contact_person_internal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('record_type', ''), _negated=True), ('record_type__in', ['ORDERED', 'INROOM', 'LENT', 'LOST', 'REMOVED'])), name='core_record_valid_record_type_required'),
        ),
    ]
