# Generated by Django 5.2.1 on 2025-06-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_record_core_record_valid_record_type_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('can_inventorize', 'Can inventorize devices')], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventories'},
        ),
    ]
