# Generated by Django 5.2.3 on 2025-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='device_search_tenant_aware',
            field=models.BooleanField(default=True, help_text='If set, the device search will only return devices for the current tenant.', verbose_name='Device search tenant aware'),
        ),
    ]
