# Generated by Django 6.0.3 on 2026-03-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_inventory_device_search_tenant_aware'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostrecord',
            options={'verbose_name': 'Lost', 'verbose_name_plural': 'Lost'},
        ),
        migrations.AlterModelOptions(
            name='removedrecord',
            options={'verbose_name': 'Removed', 'verbose_name_plural': 'Removed'},
        ),
    ]
