# Generated by Django 6.0.6 on 2026-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_move_import_models_to_dataexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='udb_person_image_hash',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
