# Generated by Django 6.0.6 on 2026-06-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_person_udb_person_image_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Bootstrap Icons class, e.g. “bi-laptop”. See https://icons.getbootstrap.com/.', max_length=64, verbose_name='Icon'),
        ),
    ]
