# Generated by Django 6.0.6 on 2026-06-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_devicetype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sync_lent_end_date',
            field=models.BooleanField(default=False, help_text="If on, the desired return date follows the borrower's UDB contract end date on each sync. Turn off to keep a custom return date.", verbose_name='Sync return date with contract end'),
        ),
    ]
