# Generated by Django 6.0.6 on 2026-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_record_sync_lent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='lent_accessories',
            field=models.TextField(blank=True, verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lent_end_date',
            field=models.DateField(blank=True, help_text='Once provided, the rental is complete', null=True, verbose_name='Returned on'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lent_note',
            field=models.TextField(blank=True, help_text='Note (lending, internal only)', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lent_reason',
            field=models.TextField(blank=True, help_text='Reason for lending', verbose_name='Reason'),
        ),
    ]
