# Generated by Django 6.0.6 on 2026-07-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_record_lent_accessories_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='core_record_valid_lent_desired_end_date',
        ),
    ]
