# Generated by Django 6.0.6 on 2026-07-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_remove_record_core_record_valid_lent_desired_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='udb_contract_contract_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='HR contract type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_contract_organization_unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='HR contract organization unit'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_contract_organizational_positions',
            field=models.CharField(blank=True, max_length=255, verbose_name='HR contract organizational positions'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_contract_planned_checkin',
            field=models.DateField(blank=True, null=True, verbose_name='HR contract planned check-in'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_contract_planned_checkout',
            field=models.DateField(blank=True, null=True, verbose_name='HR contract planned check-out'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_data_updated_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Last HR API update'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_email_internal_business',
            field=models.EmailField(blank=True, max_length=320, null=True, unique=True, verbose_name='HR internal business email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_email_private',
            field=models.EmailField(blank=True, max_length=320, null=True, unique=True, verbose_name='HR private email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HR first name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_image',
            field=models.ImageField(blank=True, upload_to='person_images/', verbose_name='HR person image'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_image_hash',
            field=models.CharField(blank=True, editable=False, max_length=32, verbose_name='HR person image hash'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HR last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='udb_person_uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='HR person UUID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sync_lent_end_date',
            field=models.BooleanField(default=False, help_text="If on, the desired return date follows the borrower's HR contract end date on each sync. Turn off to keep a custom return date.", verbose_name='Sync return date with contract end'),
        ),
    ]
