# Generated by Django 6.0.6 on 2026-07-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_person_udb_contract_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inroomrecord',
            options={'verbose_name': 'Room assignment', 'verbose_name_plural': 'Room assignments'},
        ),
        migrations.AlterModelOptions(
            name='orderedrecord',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='record',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='Order date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lent_desired_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Desired return date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='lent_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lent from'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('INROOM', 'In room'), ('LENT', 'Lent'), ('LOST', 'Not locatable'), ('REMOVED', 'Removed')], db_index=True, max_length=20, verbose_name='Record type'),
        ),
        migrations.AlterField(
            model_name='record',
            name='removed_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Removed on'),
        ),
        migrations.AlterField(
            model_name='record',
            name='removed_info',
            field=models.TextField(blank=True, null=True, verbose_name='Whereabouts'),
        ),
    ]
