# Generated by Django 6.0.7 on 2026-07-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_translate_record_type_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('transition_can_order_device', 'Transition: Can record a device as ordered'), ('transition_can_locate_device', 'Transition: Can localise a device for the first time'), ('transition_can_relocate_device', 'Transition: Can move a device to another room'), ('transition_can_lend_device', 'Transition: Can lend a device and take it back'), ('transition_can_lose_device', 'Transition: Can mark a device as not locatable'), ('transition_can_find_device', 'Transition: Can mark a lost device as found'), ('transition_can_remove_device', 'Transition: Can remove (decommission) a device'), ('transition_can_restore_device', 'Transition: Can restore a removed device to not-locatable'), ('transition_can_recover_device', 'Transition: Can recover a removed device into a room')], 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
    ]
