# Generated by Django 6.0.7 on 2026-07-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_translate_record_type_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'permissions': [('can_order_device', 'Can record a device as ordered'), ('can_locate_device', 'Can localise a device for the first time'), ('can_relocate_device', 'Can move a device to another room'), ('can_lend_device', 'Can lend a device and take it back'), ('can_lose_device', 'Can mark a device as not locatable'), ('can_find_device', 'Can mark a lost device as found'), ('can_remove_device', 'Can remove (decommission) a device'), ('can_restore_device', 'Can restore a removed device to not-locatable'), ('can_recover_device', 'Can recover a removed device into a room')], 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
    ]
