# Generated by Django 6.0.7 on 2026-07-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_grant_lifecycle_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='device',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='prefix',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='modified_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='historicaldevice',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='link',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='link',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text="ALWAYS provide an email address, otherwise we won't be able to contact the borrowers.", max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='record',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='record',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='room',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='room',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Room number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
    ]
