# Generated by Django 6.0.7 on 2026-08-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_attachment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='url',
            field=models.URLField(blank=True, help_text='Optional link to a web resource for this device - for example its own management web interface, a vendor support page or an online manual. ', verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='historicaldevice',
            name='url',
            field=models.URLField(blank=True, help_text='Optional link to a web resource for this device - for example its own management web interface, a vendor support page or an online manual. ', verbose_name='URL'),
        ),
    ]
