# Generated by Django 6.0.8 on 2026-08-27 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_device_url_historicaldevice_url'),
        ('dataexchange', '0006_alter_udbsyncconfiguration_options_and_more'),
        ('tenants', '0004_tenant_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['created_at'], name='core_device_created_5afe08_idx'),
        ),
    ]
