# Generated by Django 6.1.1 on 2026-10-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_device_core_device_created_5afe08_idx'),
        ('tenants', '0004_tenant_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='device_search_tenant_aware',
            field=models.BooleanField(default=True, help_text="If set, the device search will only return devices of the user's tenants.", verbose_name='Device search tenant aware'),
        ),
    ]
