# Generated by Django 4.0.5 on 2022-06-06 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_person_udb_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Benutzername (denormalized)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_things', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='smallstuff.thing')),
                ('unassigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unassigned_things', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assigned thing',
                'verbose_name_plural': 'Assigned things',
                'ordering': ['person__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='thing',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_ou_name'),
        ),
        migrations.AddConstraint(
            model_name='thing',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='unique_ou_slug'),
        ),
    ]
