# Generated by Django 4.0.5 on 2022-06-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallstuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'ordering': ['name']},
        ),
    ]
