# Generated by Django 5.0.4 on 2024-07-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_inventory_options'),
        ('smallstuff', '0003_alter_assignedthing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedthing',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person'),
        ),
        migrations.AlterField(
            model_name='assignedthing',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smallstuff.thing'),
        ),
    ]
