# Generated by Django 6.0.3 on 2026-03-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallstuff', '0004_alter_assignedthing_person_alter_assignedthing_thing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedthing',
            options={'ordering': ['person__last_name'], 'verbose_name': 'Stuff', 'verbose_name_plural': 'Stuff'},
        ),
    ]
