# Generated by Django 6.0.7 on 2026-07-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallstuff', '0005_alter_assignedthing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
    ]
