# Generated by Django 4.0 on 2022-01-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_super_tenant', models.BooleanField(default=False, help_text='If set to True, users of this tenant could view and edit all assets.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups which define this tenant.', to='auth.Group')),
            ],
        ),
    ]
