# Generated by Django 4.0 on 2022-01-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='is_super_tenant',
        ),
    ]
