# Generated by Django 4.0 on 2022-01-09 01:00

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_tenant_is_super_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
