# Generated by Django 6.0.6 on 2026-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Responsible contact/IT address for this tenant. Receives the overdue-lending copies (CC or reroute) for this tenant's devices and is shown in email footers. Falls back to the Branding IT dept email, then DEFAULT_FROM_EMAIL.", max_length=254),
        ),
    ]
