# SPDX-FileCopyrightText: 2024 Thomas Breitner
#
# SPDX-License-Identifier: EUPL-1.2

# Generated by Django 6.0.4 on 2026-06-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexchange', '0002_rename_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importerlist',
            name='file',
            field=models.FileField(help_text='Valide Spaltenköpfe: <br>SAP_ID<br>ROOM<br>EDV_ID<br>DEVICE_TYPE<br>SERIAL_NUMBER<br>MANUFACTURER<br>SERIES<br>SUPPLIER<br>PURCHASE_DATE<br>WARRANTY_EXPIRATION_DATE<br>CONTRACT_EXPIRATION_DATE<br>COST_CENTRE<br>BOOK_VALUE<br>NOTE<br>MAC_ADDRESS<br>EXTRA_MAC_ADDRESSES<br>NICK_NAME<br>IS_LENTABLE<br>IS_LICENCE<br>RECORD_TYPE<br>RECORD_NOTE<br>REMOVED_DATE<br>ORDER_NUMBER<br>LENDER_FIRST_NAME<br>LENDER_LAST_NAME<br>LENDER_EMAIL<br>LENDER_OU<br>LENT_START_DATE<br>LENT_DESIRED_END_DATE<br>LENT_END_DATE<br>LENT_NOTE<br>LENT_REASON<br>LENT_ACCESSORIES', upload_to='imported_csv', verbose_name='CSV-Datei'),
        ),
    ]
