# Generated by Django 6.0.6 on 2026-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexchange', '0003_alter_importerlist_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdbSyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='If unchecked, the periodic sync and the management command exit immediately.')),
                ('url', models.URLField(blank=True, help_text='Complete URL of the UDB contracts API endpoint or a ready-made JSON dump, without a query string — e.g. <code>https://udb2.example.org/api/external_interface/contracts/</code>. Filters and requested fields are appended by the code (a static JSON file simply ignores them).', verbose_name='UDB URL')),
                ('api_token', models.CharField(blank=True, help_text='Sent as the <code>X-API-KEY</code> header. Stored in plaintext in the database.', max_length=255, verbose_name='UDB API token')),
            ],
            options={
                'verbose_name': 'UDB Sync Configuration',
                'verbose_name_plural': 'UDB Sync Configuration',
            },
        ),
    ]
