# Generated by Django 6.0.6 on 2026-06-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexchange', '0004_udbsyncconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdbSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], max_length=10, verbose_name='Status')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='Zusammenfassung')),
                ('messages', models.TextField(blank=True, editable=False, verbose_name='DLCDB-Ausgaben')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
            ],
            options={
                'verbose_name': 'UDB Sync Run',
                'verbose_name_plural': 'UDB Sync Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='importerlist',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='importerlist',
            name='summary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zusammenfassung'),
        ),
        migrations.AddField(
            model_name='removerlist',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='removerlist',
            name='summary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Zusammenfassung'),
        ),
        migrations.AlterField(
            model_name='importerlist',
            name='messages',
            field=models.TextField(blank=True, editable=False, verbose_name='DLCDB-Ausgaben'),
        ),
        migrations.AlterField(
            model_name='removerlist',
            name='messages',
            field=models.TextField(blank=True, editable=False, verbose_name='DLCDB-Ausgaben'),
        ),
        migrations.AlterField(
            model_name='udbsyncconfiguration',
            name='url',
            field=models.URLField(blank=True, help_text='Complete URL of the UDB contracts API endpoint or a ready-made JSON dump, without a query string — e.g. <code>https://udb.example.org/api/external_interface/contracts/</code>. Filters and requested fields are appended by the code (a static JSON file simply ignores them).', verbose_name='UDB URL'),
        ),
    ]
