# Generated by Django 6.0.6 on 2026-07-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexchange', '0005_udbsyncrun_importerlist_status_importerlist_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='udbsyncconfiguration',
            options={'verbose_name': 'HR API Sync Configuration', 'verbose_name_plural': 'HR API Sync Configuration'},
        ),
        migrations.AlterModelOptions(
            name='udbsyncrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'HR API Sync Run', 'verbose_name_plural': 'HR API Sync Runs'},
        ),
        migrations.AlterField(
            model_name='udbsyncconfiguration',
            name='api_token',
            field=models.CharField(blank=True, help_text='Sent as the <code>X-API-KEY</code> header. Stored in plaintext in the database.', max_length=255, verbose_name='HR API token'),
        ),
        migrations.AlterField(
            model_name='udbsyncconfiguration',
            name='url',
            field=models.URLField(blank=True, help_text='Complete URL of the HR contracts API endpoint or a ready-made JSON dump, without a query string — e.g. <code>https://hr.example.org/api/external_interface/contracts/</code>. Filters and requested fields are appended by the code (a static JSON file simply ignores them).', verbose_name='HR API URL'),
        ),
    ]
