# Generated by Django 6.1.1 on 2026-09-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataexchange', '0006_alter_udbsyncconfiguration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importerlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importerlist',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AddField(
            model_name='removerlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='removerlist',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AddField(
            model_name='udbsyncrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='udbsyncrun',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username (denormalized)'),
        ),
        migrations.AlterField(
            model_name='importerlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='importerlist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='removerlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='removerlist',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='udbsyncrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='udbsyncrun',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
