# Generated by Django 6.1.1 on 2026-10-02 07:55

import django.db.models.deletion
from django.db import migrations, models


def derive_tenant_from_devices(apps, schema_editor):
    """
    Legacy imports without tenant (superusers used to import without one) are
    invisible in every tenant-scoped list. Give each the tenant of its devices
    when all of them share exactly one. Imports without devices, or with devices
    in several tenants or without tenant, stay without tenant.
    """
    ImporterList = apps.get_model("dataexchange", "ImporterList")
    Device = apps.get_model("core", "Device")
    for importer_list in ImporterList.objects.filter(tenant__isnull=True):
        tenant_ids = set(Device.objects.filter(imported_by=importer_list).values_list("tenant_id", flat=True))
        if len(tenant_ids) == 1 and None not in tenant_ids:
            # A data fix: update() keeps the import's audit fields as they are.
            ImporterList.objects.filter(pk=importer_list.pk).update(tenant_id=tenant_ids.pop())


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_device_tenant_protect'),
        ('dataexchange', '0007_operationlog_audit_user'),
        ('tenants', '0005_tenant_audit_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importerlist',
            name='tenant',
            field=models.ForeignKey(help_text='Import as given tenant.', null=True, on_delete=django.db.models.deletion.PROTECT, to='tenants.tenant'),
        ),
        migrations.RunPython(derive_tenant_from_devices, migrations.RunPython.noop),
    ]
