# Generated by Django 4.1.3 on 2022-11-17 21:05

from django.db import migrations, models
import dlcdb.organization.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "organization_name_en",
                    models.CharField(
                        default="A Company that Makes Everything",
                        help_text="Company, institute, site name (english version).",
                        max_length=255,
                        verbose_name="Organization Name (EN)",
                    ),
                ),
                (
                    "organization_name_de",
                    models.CharField(
                        default="A Company that Makes Everything",
                        help_text="Company, institute, site name (german version).",
                        max_length=255,
                        verbose_name="Organization Name (DE)",
                    ),
                ),
                (
                    "organization_abbr",
                    models.CharField(
                        default="ACME",
                        help_text="Company, institute, site abbreviation.",
                        max_length=255,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "organization_street",
                    models.CharField(
                        blank=True, help_text="Street and house number. Used in printouts etc.", max_length=255
                    ),
                ),
                (
                    "organization_zip_code",
                    models.CharField(
                        blank=True,
                        help_text="Used in printouts etc.",
                        max_length=255,
                        verbose_name="Organization ZIP Code",
                    ),
                ),
                ("organization_city", models.CharField(blank=True, help_text="Used in printouts etc.", max_length=255)),
                (
                    "organization_url",
                    models.URLField(blank=True, help_text="Used in printouts etc.", verbose_name="Organization URL"),
                ),
                (
                    "organization_logo_white",
                    models.FileField(
                        blank=True,
                        help_text="Logo file. SVG, white foreground, transparent background",
                        null=True,
                        upload_to="branding/",
                        validators=[dlcdb.organization.models.validate_logo_image_file_extension],
                        verbose_name="Logo file (white)",
                    ),
                ),
                (
                    "organization_logo_black",
                    models.FileField(
                        blank=True,
                        help_text="Logo file. SVG, white foreground, transparent background",
                        null=True,
                        upload_to="branding/",
                        validators=[dlcdb.organization.models.validate_logo_image_file_extension],
                        verbose_name="Logo file (black)",
                    ),
                ),
                (
                    "organization_figurative_mark",
                    models.FileField(
                        blank=True,
                        help_text="Bildmarke, quasi Logo ohne Wortmarke.",
                        null=True,
                        upload_to="branding/",
                        validators=[dlcdb.organization.models.validate_logo_image_file_extension],
                        verbose_name="Figurative Mark/Bildmarke",
                    ),
                ),
                (
                    "organization_favicon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="branding/",
                        validators=[dlcdb.organization.models.validate_logo_image_file_extension],
                        verbose_name="Favicon file",
                    ),
                ),
                (
                    "organization_it_dept_name",
                    models.CharField(
                        blank=True,
                        help_text="Wording for the IT department. Used in printouts etc.",
                        max_length=255,
                        verbose_name="IT Department Name",
                    ),
                ),
                (
                    "organization_it_dept_phone",
                    models.CharField(blank=True, max_length=255, verbose_name="IT Department Phone"),
                ),
                (
                    "organization_it_dept_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="IT Department Email"),
                ),
            ],
            options={
                "verbose_name": "Branding",
                "verbose_name_plural": "Branding",
            },
        ),
    ]
