# Generated by Django 4.1.3 on 2022-11-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_branding_documentation_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branding",
            name="documentation_url",
            field=models.URLField(
                blank=True,
                default="https://dlcdb.pages.gwdg.de/django-dlcdb/",
                help_text="If you host the documentation on your own, provide the URL here.",
            ),
        ),
    ]
