# Generated by Django 5.0.2 on 2024-03-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_branding_room_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='organization_abbr',
            field=models.CharField(default='DLCDB', help_text='Company, institute, site abbreviation.', max_length=255, verbose_name='Abbreviation'),
        ),
    ]
