# Generated by Django 5.0.8 on 2024-09-02 09:31

import dlcdb.organization.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_branding_organization_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='organization_logo_black',
            field=models.FileField(blank=True, help_text='Logo file. SVG, black foreground, transparent background. Used in PDF printouts.', null=True, upload_to='branding/', validators=[dlcdb.organization.models.validate_logo_image_file_extension], verbose_name='Logo file (black)'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='organization_logo_white',
            field=models.FileField(blank=True, help_text='Logo file. SVG, white foreground, transparent background. Used in the main navigation bar/site header.', null=True, upload_to='branding/', validators=[dlcdb.organization.models.validate_logo_image_file_extension], verbose_name='Logo file (white)'),
        ),
    ]
