# Generated by Django 6.0.6 on 2026-07-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_branding_licenses_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='organization_favicon',
        ),
    ]
