# Generated by Django 6.1.1 on 2026-10-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_remove_branding_organization_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='documentation_url',
            field=models.URLField(blank=True, default='https://tombreit.github.io/django-dlcdb/', help_text='If you host the documentation on your own, provide the URL here.'),
        ),
    ]
